import React, { useState } from 'react';
import { ChevronDown } from 'lucide-react';

export const ALL_FAQS = [
  {
    q: 'What files can I upload?',
    a: 'Unbrand Agency accepts campaign data exported as CSV or Excel (.xls/.xlsx) files, up to 50MB. PDF and image uploads are not currently supported.',
  },
  {
    q: 'Does the platform support Excel?',
    a: 'Yes. Both CSV and Excel (.xls/.xlsx) files are fully supported for import, including guided column mapping before data is saved.',
  },
  {
    q: 'How does report type detection work?',
    a: 'When you import data, Unbrand Agency automatically classifies each report as Lead Generation, Sales Campaign or Sales Data based on the metrics present — there is no manual toggle to get wrong. Dashboards and PDF reports automatically use the correct terminology (Leads/CPL for lead generation, Purchases/Revenue/ROAS for sales) for the detected type.',
  },
  {
    q: 'Can I create reports for multiple clients?',
    a: 'Yes. Each agency account can manage multiple client profiles, each with its own uploads, dashboard and report history. Client limits depend on your plan: 2 on Free, 15 on Pro, unlimited on Agency.',
  },
  {
    q: 'Can I add my agency branding?',
    a: 'Yes, on the Pro and Agency plans. Your agency logo and brand colors are applied to generated PDF reports.',
  },
  {
    q: 'What PDF themes are available?',
    a: 'Five report themes are available: Professional Blue, Purple Gradient, Emerald, Dark, and Minimal Black & White. Every plan can choose any theme.',
  },
  {
    q: 'Are platform integrations available?',
    a: 'Direct auto-sync with Meta Ads, Google Ads, LinkedIn Ads and Shopify is on our roadmap and marked Coming Soon. Today, campaign data is brought in via CSV or Excel import.',
  },
  {
    q: 'How are payments processed?',
    a: 'Subscription payments are processed securely through Razorpay. Card and payment details are handled by Razorpay, not stored on Unbrand Agency servers.',
  },
  {
    q: 'Can I download previous reports?',
    a: 'Yes. Every generated report is saved to your report history and can be downloaded again at any time.',
  },
  {
    q: 'Is manual data entry supported?',
    a: 'Not currently. Campaign data is brought into Unbrand Agency via CSV or Excel upload.',
  },
  {
    q: 'Are the automated insights powered by AI like ChatGPT?',
    a: 'No. Insights and recommendations are generated by rule-based analysis of the campaign metrics in your imported data — not a generative AI or language model.',
  },
];

export const HOME_FAQS = ALL_FAQS.filter((item) =>
  [
    'What files can I upload?',
    'How does report type detection work?',
    'Can I add my agency branding?',
    'Are platform integrations available?',
    'How are payments processed?',
  ].includes(item.q)
);

export default function FaqAccordion({ items }) {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <div>
      {items.map((item, i) => {
        const open = openIndex === i;
        return (
          <div className="pub-faq-item" key={item.q}>
            <button
              type="button"
              className="pub-faq-q"
              onClick={() => setOpenIndex(open ? -1 : i)}
              aria-expanded={open}
            >
              {item.q}
              <ChevronDown
                size={18}
                style={{ transform: open ? 'rotate(180deg)' : 'none', transition: 'transform .2s', flexShrink: 0, color: 'var(--text3)' }}
              />
            </button>
            {open && <div className="pub-faq-a">{item.a}</div>}
          </div>
        );
      })}
    </div>
  );
}
